- title: <a href='https://www.nationalacademies.org/trb/transportation-research-board'>Transportation Research Board (TRB)</a>
  type: time_table
  contents:
    - title: Freight & Marine Subcommittee of Young Members Coordinating Council
      institution: Chair
      year: 2021 - now
      description:
        - title: TRB Annual Meeting 2023
          contents:
            - Sub-description 1.
            - Sub-description 2.
    - title: TRB Standing Committee on Freight Transportation Data
      institution: Member
      year: 2021 - now
    - title: TRB Standing Committee on Intermodal Freight Transport
      institution: Member
      year: 2020 - now
    - title: TRB Joint Subcommittee on Intermodal Freight Terminal Design and Operations
      institution: Member
      year: 2020 - 2022
    - title: TRB Standing Committee on Intermodal Freight Terminal Design and Operations
      institution: Member
      year: 2016 - 2019


- title: Editorial Service
  type: time_table
  contents:
    - title: <a href='https://www.hindawi.com/journals/ace/'>Advances in Civil Engineering</a>
      institution: Academic Editor
      year: 2022 - now
    - title: <a href='https://www.frontiersin.org/journals/future-transportation'>Frontiers in Future Transportation</a>
      institution: Review Editor for Transport Safety
      year: 2021 - now
    - title: National Cooperative Highway Research Program Project, <a href='https://apps.trb.org/cmsfeed/TRBNetProjectDisplay.asp?ProjectID=4957'>Integrating Resiliency into Transportation System Operations</a>
      institution: Panel Member
      year: 2021 - now
    - title: <a href='https://www.mdpi.com/journal/sustainability'>Sustainability</a>
      institution: Topic Editor
      year: 2020 - now


- title: Peer Review
  type: time_table
  contents:
    - title: Journal Referee
      institution: Scientific Reports, Transportation Research Record, IEEE Access, Journal of Advanced Transportation, Sustainability, Accident Analysis & Prevention (Outstanding Reviewer in 2018)
      year: 2017 - now
    - title: Conference Referee
      institution: Transportation Research Board Annual Meeting, International Conference on Transportation & Development
      year: 2017 - now
